-- 集成测试隔离建表脚本：在独立库 howe-ai-itest 内建管理员助手的全部事实表。
-- 与生产脚本 ai_admin_assistant_phase_one.sql 的建表语句保持一致（CREATE TABLE IF NOT EXISTS，幂等可重复执行），
-- 但只保留事实表，不含 sys_config/sys_menu 参数与菜单（集成测试不需要这些）。
-- 该脚本只在测试库执行，绝不触碰业务库 howe-system。

CREATE TABLE IF NOT EXISTS ai_agent (agent_id BIGINT AUTO_INCREMENT PRIMARY KEY, agent_key VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, draft_version INT NOT NULL DEFAULT 0, published_version_id BIGINT NULL, status CHAR(1) NOT NULL DEFAULT '0', draft_json JSON NOT NULL, create_by VARCHAR(64), create_time DATETIME, update_by VARCHAR(64), update_time DATETIME, UNIQUE KEY uk_ai_agent_key (agent_key), KEY idx_ai_agent_status (status));
CREATE TABLE IF NOT EXISTS ai_agent_version (version_id BIGINT AUTO_INCREMENT PRIMARY KEY, agent_id BIGINT NOT NULL, version_no INT NOT NULL, system_prompt TEXT NOT NULL, route_snapshot JSON NOT NULL, tool_snapshot JSON NOT NULL, capability_snapshot JSON NOT NULL, budget_snapshot JSON NOT NULL, published_by VARCHAR(64), published_time DATETIME, UNIQUE KEY uk_ai_agent_version (agent_id, version_no), KEY idx_ai_agent_version_agent (agent_id));
CREATE TABLE IF NOT EXISTS ai_agent_tool (agent_tool_id BIGINT AUTO_INCREMENT PRIMARY KEY, agent_id BIGINT NOT NULL, tool_key VARCHAR(128) NOT NULL, permission_json JSON NOT NULL, enabled CHAR(1) NOT NULL DEFAULT '1', UNIQUE KEY uk_ai_agent_tool (agent_id, tool_key));
CREATE TABLE IF NOT EXISTS ai_provider (provider_id BIGINT AUTO_INCREMENT PRIMARY KEY, provider_key VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, provider_type VARCHAR(32) NOT NULL, enabled CHAR(1) NOT NULL DEFAULT '0', config_json JSON NOT NULL, UNIQUE KEY uk_ai_provider_key (provider_key));
CREATE TABLE IF NOT EXISTS ai_channel (channel_id BIGINT AUTO_INCREMENT PRIMARY KEY, provider_id BIGINT NULL, channel_key VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, endpoint VARCHAR(255) NULL, enabled CHAR(1) NOT NULL DEFAULT '0', config_json JSON NOT NULL, UNIQUE KEY uk_ai_channel_key (channel_key), KEY idx_ai_channel_provider (provider_id, enabled));
CREATE TABLE IF NOT EXISTS ai_channel_key (key_id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_id BIGINT NOT NULL, secret_cipher TEXT NOT NULL, key_version INT NOT NULL DEFAULT 1, enabled CHAR(1) NOT NULL DEFAULT '1', created_time DATETIME NOT NULL, replaced_time DATETIME NULL, KEY idx_ai_channel_key_channel (channel_id, enabled));
CREATE TABLE IF NOT EXISTS ai_model (model_id BIGINT AUTO_INCREMENT PRIMARY KEY, channel_id BIGINT NOT NULL, model_key VARCHAR(128) NOT NULL, model_name VARCHAR(128), context_window INT, enabled CHAR(1) NOT NULL DEFAULT '0', capabilities JSON NOT NULL, UNIQUE KEY uk_ai_model_channel_key (channel_id, model_key));
CREATE TABLE IF NOT EXISTS ai_route_policy (policy_id BIGINT AUTO_INCREMENT PRIMARY KEY, policy_key VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, enabled CHAR(1) NOT NULL DEFAULT '1', policy_json JSON NOT NULL, UNIQUE KEY uk_ai_route_policy_key (policy_key));
CREATE TABLE IF NOT EXISTS ai_route_item (route_item_id BIGINT AUTO_INCREMENT PRIMARY KEY, policy_id BIGINT NOT NULL, channel_id BIGINT NOT NULL, model_id BIGINT NOT NULL, priority INT NOT NULL, retry_json JSON NOT NULL, fallback_json JSON NOT NULL, enabled CHAR(1) NOT NULL DEFAULT '1', UNIQUE KEY uk_ai_route_item (policy_id, channel_id, model_id), KEY idx_ai_route_priority (policy_id, priority));
CREATE TABLE IF NOT EXISTS ai_model_price (price_id BIGINT AUTO_INCREMENT PRIMARY KEY, model_id BIGINT NOT NULL, currency CHAR(3) NOT NULL, input_price DECIMAL(18,8) NOT NULL, output_price DECIMAL(18,8) NOT NULL, effective_from DATETIME NOT NULL, effective_to DATETIME NULL, UNIQUE KEY uk_ai_model_price (model_id, effective_from));
CREATE TABLE IF NOT EXISTS ai_conversation (conversation_id BIGINT AUTO_INCREMENT PRIMARY KEY, agent_id BIGINT NOT NULL, user_id BIGINT, title VARCHAR(255), status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE', create_time DATETIME, update_time DATETIME, KEY idx_ai_conversation_user (user_id, update_time));
CREATE TABLE IF NOT EXISTS ai_message (message_id BIGINT AUTO_INCREMENT PRIMARY KEY, conversation_id BIGINT NOT NULL, run_id BIGINT NULL, role VARCHAR(16) NOT NULL, content MEDIUMTEXT, content_summary TEXT, metadata_json JSON, create_time DATETIME NOT NULL, KEY idx_ai_message_conversation (conversation_id, message_id));
CREATE TABLE IF NOT EXISTS ai_run (run_id BIGINT AUTO_INCREMENT PRIMARY KEY, conversation_id BIGINT NOT NULL, agent_id BIGINT NOT NULL, agent_version_id BIGINT NOT NULL, status VARCHAR(32) NOT NULL, route_snapshot JSON NOT NULL, tool_snapshot JSON NOT NULL, budget_snapshot JSON NOT NULL, idempotency_key VARCHAR(128), worker_id VARCHAR(128) NULL, lease_until DATETIME NULL, heartbeat_time DATETIME NULL, recovery_count INT NOT NULL DEFAULT 0, started_time DATETIME NULL, finished_time DATETIME NULL, error_code VARCHAR(64), create_time DATETIME NOT NULL, update_time DATETIME NOT NULL, UNIQUE KEY uk_ai_run_idempotency (conversation_id, idempotency_key), KEY idx_ai_run_status (status, update_time), KEY idx_ai_run_lease (lease_until, status));
CREATE TABLE IF NOT EXISTS ai_run_event (event_id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, sequence_no BIGINT NOT NULL, event_type VARCHAR(64) NOT NULL, event_json JSON NOT NULL, idempotency_key VARCHAR(128), create_time DATETIME NOT NULL, UNIQUE KEY uk_ai_run_event_sequence (run_id, sequence_no), UNIQUE KEY uk_ai_run_event_idempotency (run_id, idempotency_key));
CREATE TABLE IF NOT EXISTS ai_run_checkpoint (checkpoint_id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, sequence_no BIGINT NOT NULL, state_json JSON NOT NULL, create_time DATETIME NOT NULL, UNIQUE KEY uk_ai_checkpoint (run_id, sequence_no));
CREATE TABLE IF NOT EXISTS ai_outbox_event (outbox_id BIGINT AUTO_INCREMENT PRIMARY KEY, aggregate_type VARCHAR(32) NOT NULL, aggregate_id BIGINT NOT NULL, event_type VARCHAR(64) NOT NULL, payload_json JSON NOT NULL, idempotency_key VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'PENDING', attempts INT NOT NULL DEFAULT 0, available_time DATETIME NOT NULL, sent_time DATETIME NULL, UNIQUE KEY uk_ai_outbox_idempotency (idempotency_key), KEY idx_ai_outbox_pending (status, available_time));
CREATE TABLE IF NOT EXISTS ai_model_call (call_id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, channel_id BIGINT, model_id BIGINT, status VARCHAR(16) NOT NULL, request_started DATETIME, request_finished DATETIME, usage_json JSON, price_snapshot JSON NOT NULL, estimated_cost DECIMAL(18,8), actual_cost DECIMAL(18,8), error_json JSON, KEY idx_ai_model_call_run (run_id));
CREATE TABLE IF NOT EXISTS ai_tool_call (tool_call_id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, tool_key VARCHAR(128) NOT NULL, idempotency_key VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, request_json JSON, result_summary TEXT, started_time DATETIME, finished_time DATETIME, UNIQUE KEY uk_ai_tool_call_idempotency (run_id, idempotency_key));
CREATE TABLE IF NOT EXISTS ai_tool_approval (approval_id BIGINT AUTO_INCREMENT PRIMARY KEY, run_id BIGINT NOT NULL, tool_call_id BIGINT NOT NULL, status VARCHAR(16) NOT NULL, requested_by VARCHAR(64), decided_by VARCHAR(64), decision_time DATETIME NULL, decision_json JSON, KEY idx_ai_tool_approval_run (run_id));
