package com.howe.ai.contract;

public enum ProviderErrorCategory {
    NETWORK_TIMEOUT, RATE_LIMITED, SERVER_ERROR, AUTHENTICATION,
    INSUFFICIENT_BALANCE, INVALID_REQUEST_SCHEMA, CONTEXT_LIMIT,
    PERMISSION_DENIED, SAFETY_REJECTED, UNKNOWN
}
